
import java.awt.Color;
import java.util.Arrays;
import java.util.Objects;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ivan
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GeneratorDistributionComboBox = new javax.swing.JComboBox<>();
        GeneratorFirstParamLabel = new javax.swing.JLabel();
        GeneratorFirstParamTextField = new javax.swing.JTextField();
        GeneratorSecondParamTextField = new javax.swing.JTextField();
        GeneratorSecondParamLabel = new javax.swing.JLabel();
        Service1FirstParamTextField = new javax.swing.JTextField();
        Service1SecondParamTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Service1SecondParamLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Service1DistributionComboBox = new javax.swing.JComboBox<>();
        Service1FirstParamLabel = new javax.swing.JLabel();
        Service2SecondParamLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Service2DistributionComboBox = new javax.swing.JComboBox<>();
        Service2FirstParamLabel = new javax.swing.JLabel();
        Service2FirstParamTextField = new javax.swing.JTextField();
        Service2SecondParamTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Operator1SecondParamLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Operator1DistributionComboBox = new javax.swing.JComboBox<>();
        Operator1FirstParamLabel = new javax.swing.JLabel();
        Operator2SecondParamLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Operator2DistributionComboBox = new javax.swing.JComboBox<>();
        Operator2FirstParamLabel = new javax.swing.JLabel();
        Operator2FirstParamTextField = new javax.swing.JTextField();
        Operator2SecondParamTextField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Operator3SecondParamLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Operator3DistributionComboBox = new javax.swing.JComboBox<>();
        Operator3FirstParamLabel = new javax.swing.JLabel();
        Operator3FirstParamTextField = new javax.swing.JTextField();
        Operator3SecondParamTextField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        Operator1FirstParamTextField = new javax.swing.JTextField();
        Operator1SecondParamTextField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GeneratorRequestCountTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RejectProbabiliytLabel = new javax.swing.JLabel();
        CalcButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 300));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Генератор");

        jLabel4.setText("Закон распределения:");

        GeneratorDistributionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Пуассона", "Эрланга" }));
        GeneratorDistributionComboBox.setEnabled(false);
        GeneratorDistributionComboBox.addActionListener(this::GeneratorDistributionComboBoxActionPerformed);

        GeneratorFirstParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        GeneratorFirstParamLabel.setText("a:");

        GeneratorFirstParamTextField.setText("8");
        GeneratorFirstParamTextField.setEnabled(false);
        GeneratorFirstParamTextField.addActionListener(this::GeneratorFirstParamTextFieldActionPerformed);

        GeneratorSecondParamTextField.setText("12");
        GeneratorSecondParamTextField.setEnabled(false);
        GeneratorSecondParamTextField.addActionListener(this::GeneratorSecondParamTextFieldActionPerformed);

        GeneratorSecondParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        GeneratorSecondParamLabel.setText("b:");

        Service1FirstParamTextField.setText("15");
        Service1FirstParamTextField.setEnabled(false);
        Service1FirstParamTextField.addActionListener(this::Service1FirstParamTextFieldActionPerformed);

        Service1SecondParamTextField.setText("15");
        Service1SecondParamTextField.setEnabled(false);
        Service1SecondParamTextField.addActionListener(this::Service1SecondParamTextFieldActionPerformed);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Обслуживающий аппарат 1");

        Service1SecondParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Service1SecondParamLabel.setText("b:");

        jLabel15.setText("Закон распределения:");

        Service1DistributionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Пуассона", "Эрланга" }));
        Service1DistributionComboBox.setEnabled(false);
        Service1DistributionComboBox.addActionListener(this::Service1DistributionComboBoxActionPerformed);

        Service1FirstParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Service1FirstParamLabel.setText("a:");

        Service2SecondParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Service2SecondParamLabel.setText("b:");

        jLabel18.setText("Закон распределения:");

        Service2DistributionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Пуассона", "Эрланга" }));
        Service2DistributionComboBox.setEnabled(false);
        Service2DistributionComboBox.addActionListener(this::Service2DistributionComboBoxActionPerformed);

        Service2FirstParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Service2FirstParamLabel.setText("a:");

        Service2FirstParamTextField.setText("30");
        Service2FirstParamTextField.setEnabled(false);
        Service2FirstParamTextField.addActionListener(this::Service2FirstParamTextFieldActionPerformed);

        Service2SecondParamTextField.setText("30");
        Service2SecondParamTextField.setEnabled(false);
        Service2SecondParamTextField.addActionListener(this::Service2SecondParamTextFieldActionPerformed);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Обслуживающий аппарат 2");

        Operator1SecondParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator1SecondParamLabel.setText("b:");

        jLabel26.setText("Закон распределения:");

        Operator1DistributionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Пуассона", "Эрланга" }));
        Operator1DistributionComboBox.setEnabled(false);
        Operator1DistributionComboBox.addActionListener(this::Operator1DistributionComboBoxActionPerformed);

        Operator1FirstParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator1FirstParamLabel.setText("a:");

        Operator2SecondParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator2SecondParamLabel.setText("b:");

        jLabel29.setText("Закон распределения:");

        Operator2DistributionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Пуассона", "Эрланга" }));
        Operator2DistributionComboBox.setEnabled(false);
        Operator2DistributionComboBox.addActionListener(this::Operator2DistributionComboBoxActionPerformed);

        Operator2FirstParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator2FirstParamLabel.setText("a:");

        Operator2FirstParamTextField.setText("30");
        Operator2FirstParamTextField.setEnabled(false);
        Operator2FirstParamTextField.addActionListener(this::Operator2FirstParamTextFieldActionPerformed);

        Operator2SecondParamTextField.setText("50");
        Operator2SecondParamTextField.setEnabled(false);
        Operator2SecondParamTextField.addActionListener(this::Operator2SecondParamTextFieldActionPerformed);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Оператор 2");

        Operator3SecondParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator3SecondParamLabel.setText("b:");

        jLabel33.setText("Закон распределения:");

        Operator3DistributionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Пуассона", "Эрланга" }));
        Operator3DistributionComboBox.setEnabled(false);
        Operator3DistributionComboBox.addActionListener(this::Operator3DistributionComboBoxActionPerformed);

        Operator3FirstParamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator3FirstParamLabel.setText("a:");

        Operator3FirstParamTextField.setText("20");
        Operator3FirstParamTextField.setEnabled(false);
        Operator3FirstParamTextField.addActionListener(this::Operator3FirstParamTextFieldActionPerformed);

        Operator3SecondParamTextField.setText("60");
        Operator3SecondParamTextField.setEnabled(false);
        Operator3SecondParamTextField.addActionListener(this::Operator3SecondParamTextFieldActionPerformed);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Оператор 3");

        Operator1FirstParamTextField.setText("15");
        Operator1FirstParamTextField.setEnabled(false);
        Operator1FirstParamTextField.addActionListener(this::Operator1FirstParamTextFieldActionPerformed);

        Operator1SecondParamTextField.setText("25");
        Operator1SecondParamTextField.setEnabled(false);
        Operator1SecondParamTextField.addActionListener(this::Operator1SecondParamTextFieldActionPerformed);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Оператор 1");

        jLabel1.setText("Количество заявок:");

        GeneratorRequestCountTextField.setText("300");
        GeneratorRequestCountTextField.setEnabled(false);
        GeneratorRequestCountTextField.addActionListener(this::GeneratorRequestCountTextFieldActionPerformed);

        jLabel3.setText("Вероятность отказа:");

        CalcButton.setText("Рассчитать");
        CalcButton.addActionListener(this::CalcButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Operator1DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Operator1FirstParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator1FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator1SecondParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator1SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Operator2DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(GeneratorDistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GeneratorRequestCountTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GeneratorFirstParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GeneratorFirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GeneratorSecondParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GeneratorSecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Operator2FirstParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator2FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator2SecondParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator2SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Operator3DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Operator3FirstParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator3FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator3SecondParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Operator3SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Service1DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Service1FirstParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Service1FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Service1SecondParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Service1SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Service2DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Service2FirstParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Service2FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Service2SecondParamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Service2SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CalcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RejectProbabiliytLabel))
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GeneratorDistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeneratorFirstParamLabel)
                    .addComponent(GeneratorFirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneratorSecondParamLabel)
                    .addComponent(GeneratorSecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(GeneratorRequestCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(Operator1DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Operator1FirstParamLabel)
                            .addComponent(Operator1FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Operator1SecondParamLabel)
                            .addComponent(Operator1SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(Operator2DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Operator2FirstParamLabel)
                            .addComponent(Operator2FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Operator2SecondParamLabel)
                            .addComponent(Operator2SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(Operator3DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Operator3FirstParamLabel)
                            .addComponent(Operator3FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Operator3SecondParamLabel)
                            .addComponent(Operator3SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Service1DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Service1FirstParamLabel)
                            .addComponent(Service1FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Service1SecondParamLabel)
                            .addComponent(Service1SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Service2DistributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Service2FirstParamLabel)
                            .addComponent(Service2FirstParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Service2SecondParamLabel)
                            .addComponent(Service2SecondParamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RejectProbabiliytLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneratorFirstParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratorFirstParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneratorFirstParamTextFieldActionPerformed

    private void GeneratorSecondParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratorSecondParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneratorSecondParamTextFieldActionPerformed

    private void Service1FirstParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service1FirstParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Service1FirstParamTextFieldActionPerformed

    private void Service1SecondParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service1SecondParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Service1SecondParamTextFieldActionPerformed

    private void Service1DistributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service1DistributionComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String distributionName = Objects.requireNonNull(Service1DistributionComboBox.getSelectedItem()).toString();
            DistributionsType serviceDistribution = DistributionsType.fromDisplayName(distributionName);
            
            switch(serviceDistribution){
                case DistributionsType.UNIFORM -> {
                    Service1FirstParamLabel.setText("a:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("b:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    Service1FirstParamLabel.setText("mu:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("D[x]:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    Service1FirstParamLabel.setText("k:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("lambda:");
                    Service1SecondParamTextField.setEnabled(true);
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }   
    }//GEN-LAST:event_Service1DistributionComboBoxActionPerformed

    private void Service2DistributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service2DistributionComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String distributionName = Objects.requireNonNull(Service2DistributionComboBox.getSelectedItem()).toString();
            DistributionsType serviceDistribution = DistributionsType.fromDisplayName(distributionName);
            
            switch(serviceDistribution){
                case DistributionsType.UNIFORM -> {
                    Service1FirstParamLabel.setText("a:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("b:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    Service1FirstParamLabel.setText("mu:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("D[x]:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    Service1FirstParamLabel.setText("k:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("lambda:");
                    Service1SecondParamTextField.setEnabled(true);
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_Service2DistributionComboBoxActionPerformed

    private void Service2FirstParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service2FirstParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Service2FirstParamTextFieldActionPerformed

    private void Service2SecondParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Service2SecondParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Service2SecondParamTextFieldActionPerformed

    private void Operator1DistributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator1DistributionComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String distributionName = Objects.requireNonNull(Operator1DistributionComboBox.getSelectedItem()).toString();
            DistributionsType distribution = DistributionsType.fromDisplayName(distributionName);
            
            switch(distribution){
                case DistributionsType.UNIFORM -> {
                    Service1FirstParamLabel.setText("a:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("b:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    Service1FirstParamLabel.setText("mu:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("D[x]:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    Service1FirstParamLabel.setText("k:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("lambda:");
                    Service1SecondParamTextField.setEnabled(true);
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_Operator1DistributionComboBoxActionPerformed

    private void Operator2DistributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator2DistributionComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String distributionName = Objects.requireNonNull(Operator2DistributionComboBox.getSelectedItem()).toString();
            DistributionsType distribution = DistributionsType.fromDisplayName(distributionName);
            
            switch(distribution){
                case DistributionsType.UNIFORM -> {
                    Service1FirstParamLabel.setText("a:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("b:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    Service1FirstParamLabel.setText("mu:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("D[x]:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    Service1FirstParamLabel.setText("k:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("lambda:");
                    Service1SecondParamTextField.setEnabled(true);
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_Operator2DistributionComboBoxActionPerformed

    private void Operator2FirstParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator2FirstParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator2FirstParamTextFieldActionPerformed

    private void Operator2SecondParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator2SecondParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator2SecondParamTextFieldActionPerformed

    private void Operator3DistributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator3DistributionComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String distributionName = Objects.requireNonNull(Operator3DistributionComboBox.getSelectedItem()).toString();
            DistributionsType distribution = DistributionsType.fromDisplayName(distributionName);
            
            switch(distribution){
                case DistributionsType.UNIFORM -> {
                    Service1FirstParamLabel.setText("a:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("b:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    Service1FirstParamLabel.setText("mu:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("D[x]:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    Service1FirstParamLabel.setText("k:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("lambda:");
                    Service1SecondParamTextField.setEnabled(true);
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_Operator3DistributionComboBoxActionPerformed

    private void Operator3FirstParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator3FirstParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator3FirstParamTextFieldActionPerformed

    private void Operator3SecondParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator3SecondParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator3SecondParamTextFieldActionPerformed

    private void Operator1FirstParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator1FirstParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator1FirstParamTextFieldActionPerformed

    private void Operator1SecondParamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Operator1SecondParamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Operator1SecondParamTextFieldActionPerformed

    private void GeneratorDistributionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratorDistributionComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String distributionName = Objects.requireNonNull(GeneratorDistributionComboBox.getSelectedItem()).toString();
            DistributionsType distribution = DistributionsType.fromDisplayName(distributionName);
            
            switch(distribution){
                case DistributionsType.UNIFORM -> {
                    Service1FirstParamLabel.setText("a:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("b:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    Service1FirstParamLabel.setText("mu:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("D[x]:");
                    Service1SecondParamTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    Service1FirstParamLabel.setText("lambda:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("");
                    Service1SecondParamTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    Service1FirstParamLabel.setText("k:");
                    Service1FirstParamTextField.setEnabled(true);
                    Service1SecondParamLabel.setText("lambda:");
                    Service1SecondParamTextField.setEnabled(true);
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_GeneratorDistributionComboBoxActionPerformed

    private void GeneratorRequestCountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratorRequestCountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneratorRequestCountTextFieldActionPerformed

    private void CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcButtonActionPerformed
        // TODO add your handling code here:
        int requestsCount;
        ErrorLabel.setText("");
        
        try{
            requestsCount = Integer.parseInt(GeneratorRequestCountTextField.getText());
            if(requestsCount <= 0)
                throw new IllegalArgumentException("Число заявок должно быть больше нуля");
        }
        catch(NumberFormatException e)
        {
            ErrorLabel.setText("Параметры должны быть числами\n"+e.getMessage());
            return;
        }
        catch(Exception e)
        {
            ErrorLabel.setText(e.getMessage());
            return;
        }
        
        
        RandomGenerable generator = CreateDistribution(GeneratorDistributionComboBox, 
                                                        GeneratorFirstParamTextField,
                                                        GeneratorSecondParamTextField),
                        operator1 = CreateDistribution(Operator1DistributionComboBox,
                                                        Operator1FirstParamTextField,
                                                        Operator1SecondParamTextField),
                        operator2 = CreateDistribution(Operator2DistributionComboBox,
                                                        Operator2FirstParamTextField,
                                                        Operator2SecondParamTextField),
                        operator3 = CreateDistribution(Operator3DistributionComboBox,
                                                        Operator3FirstParamTextField,
                                                        Operator3SecondParamTextField),
                        service1 = CreateDistribution(Service1DistributionComboBox,
                                                        Service1FirstParamTextField,
                                                        Service1SecondParamTextField),
                        service2 = CreateDistribution(Service2DistributionComboBox,
                                                        Service2FirstParamTextField,
                                                        Service2SecondParamTextField);
        
        Simulator simulator = new Simulator(generator, 
                                            Arrays.asList(operator1, operator2, operator3),
                                            Arrays.asList(service1, service2),
                                            requestsCount,
                                            1);
        
        double eventQueueLength = simulator.eventSimulation();
        RejectProbabiliytLabel.setText(Double.toString(eventQueueLength));
    }//GEN-LAST:event_CalcButtonActionPerformed

    private RandomGenerable CreateDistribution(JComboBox<String> comboBox, 
                                               JTextField firstParamTextField, 
                                               JTextField secondParamTextField)
    {
        try
        {
            String distributionName = Objects.requireNonNull(comboBox.getSelectedItem()).toString();
            DistributionsType serviceDistribution = DistributionsType.fromDisplayName(distributionName);
            double firstParam, secondParam;
            RandomGenerable randomNumbersGenerator = new UniformDistributionRandom(5, 15);
            
            switch(serviceDistribution){
                case DistributionsType.UNIFORM -> 
                {
                    firstParam = Double.parseDouble(firstParamTextField.getText());
                    secondParam = Double.parseDouble(secondParamTextField.getText());
                    randomNumbersGenerator = new UniformDistributionRandom(Math.min(firstParam, secondParam), Math.max(firstParam, secondParam));
                }
                case DistributionsType.NORMAL ->
                {
                    
                    firstParam = Double.parseDouble(firstParamTextField.getText());
                    secondParam = Double.parseDouble(secondParamTextField.getText());
                    randomNumbersGenerator = new NormalDistributionRandom(firstParam, secondParam);
                }
                case DistributionsType.ERLANG ->
                {
                    
                    firstParam = Double.parseDouble(firstParamTextField.getText());
                    secondParam = Double.parseDouble(secondParamTextField.getText());
                    randomNumbersGenerator = new ErlangDistributionRandom((int)firstParam, secondParam);
                }
                case DistributionsType.EXPONENTIAL ->
                {
                    firstParam = Double.parseDouble(firstParamTextField.getText());
                    randomNumbersGenerator = new ExponentialDistributionRandom(firstParam);
                }
                case DistributionsType.POISSON ->
                {
                    firstParam = Double.parseDouble(firstParamTextField.getText());
                    randomNumbersGenerator = new PoissonDistributionRandom(firstParam);
                }
            }
            return randomNumbersGenerator;
        }
        catch (NullPointerException e)
        {
            throw e;
        }
        catch(NumberFormatException e)
        {
            ErrorLabel.setText("Параметры должны быть числами");
            ErrorLabel.setForeground(Color.red);
            throw e;
        }
        catch(InvalidErlangDistributionKParameterException | 
                InvalidErlangDistributionLambdaParameterException | 
                InvalidExponentialDistributionLambdaParameterException | 
                InvalidNormalDistributionVarianceParameterException |
                InvalidPoissonDistributionLambdaParameterException e)
        {
            ErrorLabel.setText(e.getMessage());
            ErrorLabel.setForeground(Color.red);
            throw e;
        }
        catch(Exception e)
        {
            ErrorLabel.setText(e.getMessage());
            ErrorLabel.setForeground(Color.red);
            throw e;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JComboBox<String> GeneratorDistributionComboBox;
    private javax.swing.JLabel GeneratorFirstParamLabel;
    private javax.swing.JTextField GeneratorFirstParamTextField;
    private javax.swing.JTextField GeneratorRequestCountTextField;
    private javax.swing.JLabel GeneratorSecondParamLabel;
    private javax.swing.JTextField GeneratorSecondParamTextField;
    private javax.swing.JComboBox<String> Operator1DistributionComboBox;
    private javax.swing.JLabel Operator1FirstParamLabel;
    private javax.swing.JTextField Operator1FirstParamTextField;
    private javax.swing.JLabel Operator1SecondParamLabel;
    private javax.swing.JTextField Operator1SecondParamTextField;
    private javax.swing.JComboBox<String> Operator2DistributionComboBox;
    private javax.swing.JLabel Operator2FirstParamLabel;
    private javax.swing.JTextField Operator2FirstParamTextField;
    private javax.swing.JLabel Operator2SecondParamLabel;
    private javax.swing.JTextField Operator2SecondParamTextField;
    private javax.swing.JComboBox<String> Operator3DistributionComboBox;
    private javax.swing.JLabel Operator3FirstParamLabel;
    private javax.swing.JTextField Operator3FirstParamTextField;
    private javax.swing.JLabel Operator3SecondParamLabel;
    private javax.swing.JTextField Operator3SecondParamTextField;
    private javax.swing.JLabel RejectProbabiliytLabel;
    private javax.swing.JComboBox<String> Service1DistributionComboBox;
    private javax.swing.JLabel Service1FirstParamLabel;
    private javax.swing.JTextField Service1FirstParamTextField;
    private javax.swing.JLabel Service1SecondParamLabel;
    private javax.swing.JTextField Service1SecondParamTextField;
    private javax.swing.JComboBox<String> Service2DistributionComboBox;
    private javax.swing.JLabel Service2FirstParamLabel;
    private javax.swing.JTextField Service2FirstParamTextField;
    private javax.swing.JLabel Service2SecondParamLabel;
    private javax.swing.JTextField Service2SecondParamTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
