/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Color;
import java.util.Objects;

/**
 *
 * @author ivan
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generatorComboBox = new javax.swing.JComboBox<>();
        generatorFirstLabel = new javax.swing.JLabel();
        generatorFirstTextField = new javax.swing.JTextField();
        generatorSecondLabel = new javax.swing.JLabel();
        generatorSecondTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        serviceComboBox = new javax.swing.JComboBox<>();
        serviceFirstLabel = new javax.swing.JLabel();
        serviceFirstTextField = new javax.swing.JTextField();
        serviceSecondLabel = new javax.swing.JLabel();
        serviceSecondTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        generatorCountTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        probabilityTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        timeStepTextField = new javax.swing.JTextField();
        rejectionCheckBox = new javax.swing.JCheckBox();
        simulateButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        generatorErrorLabel = new javax.swing.JLabel();
        serviceErrorLabel = new javax.swing.JLabel();
        paramsErrorLabel = new javax.swing.JLabel();
        eventPrincipleTextField = new javax.swing.JLabel();
        stepPrincipleTextField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Генератор:");

        jLabel2.setText("Закон распределения генератора:");

        generatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Эрланга", "Пуассона" }));
        generatorComboBox.addActionListener(this::generatorComboBoxActionPerformed);

        generatorFirstLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        generatorFirstLabel.setText("a:");

        generatorFirstTextField.addActionListener(this::generatorFirstTextFieldActionPerformed);

        generatorSecondLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        generatorSecondLabel.setText("b:");

        generatorSecondTextField.addActionListener(this::generatorSecondTextFieldActionPerformed);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Обслуживающий аппарат:");

        jLabel6.setText("Закон распределения генератора:");

        serviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Равномерное", "Нормальное", "Экспоненциальное", "Эрланга", "Пуассона" }));
        serviceComboBox.addActionListener(this::serviceComboBoxActionPerformed);

        serviceFirstLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serviceFirstLabel.setText("a:");

        serviceFirstTextField.addActionListener(this::serviceFirstTextFieldActionPerformed);

        serviceSecondLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serviceSecondLabel.setText("b:");

        serviceSecondTextField.addActionListener(this::serviceSecondTextFieldActionPerformed);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Параметры системы:");

        jLabel10.setText("Количество подаваемых генератором заявок:");

        generatorCountTextField.setText("1");

        jLabel11.setText("Вероятность отказа:");

        probabilityTextField.setText("0");
        probabilityTextField.addActionListener(this::probabilityTextFieldActionPerformed);

        jLabel12.setText("Временной шаг:");

        timeStepTextField.setText("0.1");

        rejectionCheckBox.setText("Отказанные заявки поступают обратно");
        rejectionCheckBox.addActionListener(this::rejectionCheckBoxActionPerformed);

        simulateButton.setText("Запустить симуляцию");
        simulateButton.addActionListener(this::simulateButtonActionPerformed);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Максимальная длина очереди");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Пошаговый принцип");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Событийный принцип");

        generatorErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        serviceErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        paramsErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generatorFirstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatorFirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(generatorSecondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatorSecondTextField)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(serviceFirstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceFirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(serviceSecondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceSecondTextField))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatorCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(probabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rejectionCheckBox))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(simulateButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paramsErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generatorErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stepPrincipleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(eventPrincipleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generatorComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(generatorFirstTextField)
                        .addComponent(generatorFirstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generatorSecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(generatorSecondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generatorErrorLabel)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(serviceFirstTextField)
                        .addComponent(serviceFirstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(serviceSecondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serviceSecondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(serviceErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generatorCountTextField)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(probabilityTextField)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeStepTextField)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rejectionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paramsErrorLabel)
                .addGap(12, 12, 12)
                .addComponent(simulateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eventPrincipleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stepPrincipleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatorComboBoxActionPerformed
        try{
            String generatorString = Objects.requireNonNull(generatorComboBox.getSelectedItem()).toString();
            DistributionsType generatorDistribution = DistributionsType.fromDisplayName(generatorString);
            
            switch(generatorDistribution){
                case DistributionsType.UNIFORM -> {
                    generatorFirstLabel.setText("a:");
                    generatorFirstTextField.setEnabled(true);
                    generatorSecondLabel.setText("b:");
                    generatorSecondTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    generatorFirstLabel.setText("mu:");
                    generatorFirstTextField.setEnabled(true);
                    generatorSecondLabel.setText("D[x]:");
                    generatorSecondTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    generatorFirstLabel.setText("lambda:");
                    generatorFirstTextField.setEnabled(true);
                    generatorSecondLabel.setText("");
                    generatorSecondTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    generatorFirstLabel.setText("lambda:");
                    generatorFirstTextField.setEnabled(true);
                    generatorSecondLabel.setText("");
                    generatorSecondTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    generatorFirstLabel.setText("k:");
                    generatorFirstTextField.setEnabled(true);
                    generatorSecondLabel.setText("lambda:");
                    generatorSecondTextField.setEnabled(true);
                    
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_generatorComboBoxActionPerformed

    private void generatorFirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatorFirstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generatorFirstTextFieldActionPerformed

    private void generatorSecondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatorSecondTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generatorSecondTextFieldActionPerformed

    private void serviceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceComboBoxActionPerformed
        try{
            String serviceString = Objects.requireNonNull(generatorComboBox.getSelectedItem()).toString();
            DistributionsType serviceDistribution = DistributionsType.fromDisplayName(serviceString);
            
            switch(serviceDistribution){

                case DistributionsType.UNIFORM -> {
                    serviceFirstLabel.setText("a:");
                    serviceFirstTextField.setEnabled(true);
                    serviceSecondLabel.setText("b:");
                    serviceSecondTextField.setEnabled(true);
                }
                case DistributionsType.NORMAL ->{
                    serviceFirstLabel.setText("mu:");
                    serviceFirstTextField.setEnabled(true);
                    serviceSecondLabel.setText("D[x]:");
                    serviceSecondTextField.setEnabled(true);
                }
                case DistributionsType.EXPONENTIAL ->{
                    serviceFirstLabel.setText("lambda:");
                    serviceFirstTextField.setEnabled(true);
                    serviceSecondLabel.setText("");
                    serviceSecondTextField.setEnabled(false);
                }
                case DistributionsType.POISSON ->{
                    serviceFirstLabel.setText("lambda:");
                    serviceFirstTextField.setEnabled(true);
                    serviceSecondLabel.setText("");
                    serviceSecondTextField.setEnabled(false);
                }
                case DistributionsType.ERLANG -> {
                    serviceFirstLabel.setText("k:");
                    serviceFirstTextField.setEnabled(true);
                    serviceSecondLabel.setText("lambda:");
                    serviceSecondTextField.setEnabled(true);
                    
                }
            }
            
        }
        catch(NullPointerException e)
        {
            return;
        }
        catch(Exception e)
        {
            return;
        }
    }//GEN-LAST:event_serviceComboBoxActionPerformed

    private void serviceFirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceFirstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceFirstTextFieldActionPerformed

    private void serviceSecondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSecondTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceSecondTextFieldActionPerformed

    private void probabilityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probabilityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_probabilityTextFieldActionPerformed

    private void rejectionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejectionCheckBoxActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
        int requestsCount;
        double rejectProbability, timeStep;
        boolean rejectedReturn;
        
        try{
            requestsCount = Integer.parseInt(generatorCountTextField.getText());
            if(requestsCount <= 0)
                throw new IllegalArgumentException("Число заявок должно быть больше нуля");
            rejectProbability = Double.parseDouble(probabilityTextField.getText());
            if(rejectProbability <0 || rejectProbability > 1)
                throw new IllegalArgumentException("Вероятность должна быть от 0.0 до 1.0");
            timeStep = Double.parseDouble(timeStepTextField.getText());
            if(timeStep <= 0)
                throw new IllegalArgumentException("Временной шаг должен быть больше нуля");
            rejectedReturn = rejectionCheckBox.isSelected();
        }
        catch(NumberFormatException e)
        {
            paramsErrorLabel.setText("Параметры должны быть числами\n"+e.getMessage());
            return;
        }
        catch(Exception e)
        {
            paramsErrorLabel.setText(e.getMessage());
            return;
        }
        
        String generatorString, serviceString;
        DistributionsType generatorDistribution, serviceDistribution;
        double generatorFirstParam, generatorSecondParam, serviceFirstParam, serviceSecondParam;
        Simulator simulator;
        try{
            generatorString = Objects.requireNonNull(generatorComboBox.getSelectedItem()).toString();
            generatorDistribution = DistributionsType.fromDisplayName(generatorString);
            
            switch(generatorDistribution){
                case DistributionsType.UNIFORM -> 
                {
                    generatorFirstParam = Double.parseDouble(generatorFirstTextField.getText());
                    generatorSecondParam = Double.parseDouble(generatorSecondTextField.getText());
                    simulator = new Simulator(new UniformDistributionRandom(Math.min(generatorFirstParam, generatorSecondParam), Math.max(generatorFirstParam, generatorSecondParam)), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.NORMAL ->
                {
                    
                    generatorFirstParam = Double.parseDouble(generatorFirstTextField.getText());
                    generatorSecondParam = Double.parseDouble(generatorSecondTextField.getText());
                    simulator = new Simulator(new NormalDistributionRandom(generatorFirstParam, generatorSecondParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.ERLANG ->
                {
                    
                    generatorFirstParam = Double.parseDouble(generatorFirstTextField.getText());
                    generatorSecondParam = Double.parseDouble(generatorSecondTextField.getText());
                    simulator = new Simulator(new ErlangDistributionRandom((int)generatorFirstParam, generatorSecondParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.EXPONENTIAL ->
                {
                    generatorFirstParam = Double.parseDouble(generatorFirstTextField.getText());
                    simulator = new Simulator(new ExponentialDistributionRandom(generatorFirstParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.POISSON ->
                {
                    generatorFirstParam = Double.parseDouble(generatorFirstTextField.getText());
                    simulator = new Simulator(new PoissonDistributionRandom(generatorFirstParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
            }
        }
        catch (NullPointerException e)
        {
            return;
        }
        catch(NumberFormatException e)
        {
            generatorErrorLabel.setText("Параметры должны быть числами");
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidErlangDistributionKParameterException e)
        {
            generatorErrorLabel.setText(e.getMessage());
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidErlangDistributionLambdaParameterException e)
        {
            generatorErrorLabel.setText(e.getMessage());
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidExponentialDistributionLambdaParameterException e)
        {
            generatorErrorLabel.setText(e.getMessage());
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidNormalDistributionVarianceParameterException e)
        {
            generatorErrorLabel.setText(e.getMessage());
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidPoissonDistributionLambdaParameterException e)
        {
            generatorErrorLabel.setText(e.getMessage());
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        catch(Exception e)
        {
            generatorErrorLabel.setText(e.getMessage());
            generatorErrorLabel.setForeground(Color.red);
            return;
        }
        
        try{
            serviceString = Objects.requireNonNull(serviceComboBox.getSelectedItem()).toString();
            serviceDistribution = DistributionsType.fromDisplayName(serviceString);
            
            
            switch(serviceDistribution){
                case DistributionsType.UNIFORM -> 
                {
                    serviceFirstParam = Double.parseDouble(serviceFirstTextField.getText());
                    serviceSecondParam = Double.parseDouble(serviceSecondTextField.getText());
                    simulator = new Simulator(new UniformDistributionRandom(Math.min(serviceFirstParam, serviceSecondParam), Math.max(serviceFirstParam, serviceSecondParam)), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.NORMAL ->
                {
                    
                    serviceFirstParam = Double.parseDouble(serviceFirstTextField.getText());
                    serviceSecondParam = Double.parseDouble(serviceSecondTextField.getText());
                    simulator = new Simulator(new NormalDistributionRandom(serviceFirstParam, serviceSecondParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.ERLANG ->
                {
                    
                    serviceFirstParam = Double.parseDouble(serviceFirstTextField.getText());
                    serviceSecondParam = Double.parseDouble(serviceSecondTextField.getText());
                    simulator = new Simulator(new ErlangDistributionRandom((int)serviceFirstParam, serviceSecondParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.EXPONENTIAL ->
                {
                    serviceFirstParam = Double.parseDouble(serviceFirstTextField.getText());
                    simulator = new Simulator(new ExponentialDistributionRandom(serviceFirstParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
                case DistributionsType.POISSON ->
                {
                    serviceFirstParam = Double.parseDouble(serviceFirstTextField.getText());
                    simulator = new Simulator(new PoissonDistributionRandom(serviceFirstParam), requestsCount, rejectProbability, timeStep, rejectedReturn);
                }
            }
        }
        catch (NullPointerException e)
        {
            return;
        }
        catch(NumberFormatException e)
        {
            serviceErrorLabel.setText("Параметры должны быть числами");
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidErlangDistributionKParameterException e)
        {
            serviceErrorLabel.setText(e.getMessage());
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidErlangDistributionLambdaParameterException e)
        {
            serviceErrorLabel.setText(e.getMessage());
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidExponentialDistributionLambdaParameterException e)
        {
            serviceErrorLabel.setText(e.getMessage());
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidNormalDistributionVarianceParameterException e)
        {
            serviceErrorLabel.setText(e.getMessage());
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
        catch(InvalidPoissonDistributionLambdaParameterException e)
        {
            serviceErrorLabel.setText(e.getMessage());
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
        catch(Exception e)
        {
            serviceErrorLabel.setText(e.getMessage());
            serviceErrorLabel.setForeground(Color.red);
            return;
        }
    }//GEN-LAST:event_simulateButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventPrincipleTextField;
    private javax.swing.JComboBox<String> generatorComboBox;
    private javax.swing.JTextField generatorCountTextField;
    private javax.swing.JLabel generatorErrorLabel;
    private javax.swing.JLabel generatorFirstLabel;
    private javax.swing.JTextField generatorFirstTextField;
    private javax.swing.JLabel generatorSecondLabel;
    private javax.swing.JTextField generatorSecondTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel paramsErrorLabel;
    private javax.swing.JTextField probabilityTextField;
    private javax.swing.JCheckBox rejectionCheckBox;
    private javax.swing.JComboBox<String> serviceComboBox;
    private javax.swing.JLabel serviceErrorLabel;
    private javax.swing.JLabel serviceFirstLabel;
    private javax.swing.JTextField serviceFirstTextField;
    private javax.swing.JLabel serviceSecondLabel;
    private javax.swing.JTextField serviceSecondTextField;
    private javax.swing.JButton simulateButton;
    private javax.swing.JLabel stepPrincipleTextField;
    private javax.swing.JTextField timeStepTextField;
    // End of variables declaration//GEN-END:variables
}
