/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author ivan
 */
public enum StatisticType {
    OPERATOR1_REJECTION_PROBABILITY,
    OPERATOR2_REJECTION_PROBABILITY,
    OPERATOR3_REJECTION_PROBABILITY,
    OPERATOR1_REJECTED_COUNT,
    OPERATOR2_REJECTED_COUNT,
    OPERATOR3_REJECTED_COUNT,
    OPERATOR1_PROCESSED_COUNT,
    OPERATOR2_PROCESSED_COUNT,
    OPERATOR3_PROCESSED_COUNT,
    OPERATOR1_AVERAGE_TIME,
    OPERATOR2_AVERAGE_TIME,
    OPERATOR3_AVERAGE_TIME,
    OPERATOR1_TOTAL_TIME,
    OPERATOR2_TOTAL_TIME,
    OPERATOR3_TOTAL_TIME,
    OPERATORS_AVERAGE_TIME,
    OPERATORS_PROCESSED_COUNT,
    OPERATORS_REJECTION_PROBABILITY,
    
    KITCHEN1_PROCESSED_COUNT,
    KITCHEN2_PROCESSED_COUNT,
    KITCHEN3_PROCESSED_COUNT,
    KITCHEN1_AVERAGE_TIME,
    KITCHEN2_AVERAGE_TIME,
    KITCHEN3_AVERAGE_TIME,
    KITCHEN1_TOTAL_TIME,
    KITCHEN2_TOTAL_TIME,
    KITCHEN3_TOTAL_TIME,
    KITCHENS_AVERAGE_TIME,
    
    RELEASE_PROCESSED_COUNT,
    RELEASE_AVERAGE_TIME,
    RELEASE_TOTAL_TIME
}
